"""course lifecycle status

Revision ID: 1170fbbaeccd
Revises: 2099d354cdbe
Create Date: 2026-09-28 21:36:01.536276

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1170fbbaeccd"
down_revision: Union[str, Sequence[str], None] = "2099d354cdbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "courses",
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            server_default="published",
        ),
    )
    op.create_index("ix_courses_status", "courses", ["status"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_status"), table_name="courses")
    op.drop_column("courses", "status")
    # ### end Alembic commands ###
