"""Update user profile

Revision ID: 596b8a7b40d5
Revises: 79ae36813af7
Create Date: 2026-09-30 22:17:21.914767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "596b8a7b40d5"
down_revision: Union[str, Sequence[str], None] = "79ae36813af7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.String(length=120), server_default="", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("bio", sa.String(length=500), server_default="", nullable=False),
    )
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "bio")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
