"""add course catalog metadata

Revision ID: 79ae36813af7
Revises: 1170fbbaeccd
Create Date: 2026-09-30 11:48:48.305076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79ae36813af7"
down_revision: Union[str, Sequence[str], None] = "1170fbbaeccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("cover_image_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "courses",
        sa.Column(
            "short_description",
            sa.String(length=280),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "difficulty",
            sa.String(length=32),
            nullable=False,
            server_default="beginner",
        ),
    )
    op.add_column(
        "courses",
        sa.Column("tag_names", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "tag_names")
    op.drop_column("courses", "difficulty")
    op.drop_column("courses", "short_description")
    op.drop_column("courses", "cover_image_url")
    # ### end Alembic commands ###
