"""create lecture comment

Revision ID: e1027f024c0b
Revises: b74a1b6bf7d1
Create Date: 2026-10-02 13:19:08.047739

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1027f024c0b"
down_revision: Union[str, Sequence[str], None] = "b74a1b6bf7d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lecture_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lecture_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lecture_id"], ["lectures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lecture_comments_lecture_id"),
        "lecture_comments",
        ["lecture_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lecture_comments_user_id"),
        "lecture_comments",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lecture_comments_user_id"), table_name="lecture_comments")
    op.drop_index(op.f("ix_lecture_comments_lecture_id"), table_name="lecture_comments")
    op.drop_table("lecture_comments")
    # ### end Alembic commands ###
